
2019/5/13 9:05:58 : 普通 －－ Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex [:]    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToInt64(Byte[] value, Int32 startIndex)
   at System.BitConverter.ToUInt64(Byte[] value, Int32 startIndex)
   at ESFramework.Engine.Udp.Reliable.FeedbackVacancyBody.ztLHu9QtwauVpsnsFA5(Object , Int32 )
   at ESFramework.Engine.Udp.Reliable.FeedbackVacancyBody.Parse(Byte[] buff, Int32 offset, Int32 bodyLen)
   at NP0TGVBgJ9QwLAhYTKW.XpFDH2BqcL8UtxuLtNZ.nhAVBhBQwwTsNff5q7G(Object , Int32 offset, Int32 bodyLen)
   at NP0TGVBgJ9QwLAhYTKW.XpFDH2BqcL8UtxuLtNZ.cpTVfL8dld(IPEndPoint  , Byte[]  ) 。错误类型:System.ArgumentOutOfRangeException。位置：ESFramework.Engine.Udp.Reliable.ReliableUdpEngine.udpClient_DataReceived


2019/5/13 15:24:25 : 普通 －－ Network connection is disconnected! [:]    at VY2WkBrATJKAS82x7vh.BPdVSJrxw6RMlYCfRpC.PickupResponse(Int32  , Int32  )
   at ksUUmTr8nYAtS5mI5Co.wyW5NXrMaaEwgBV24lX.iht9eSnX3R(aXwZLgSeWEc5DHdDVp8  , Nullable`1 resKey)
   at x8MZUsrTIhCCTcOQv02.agcZdrrgVBTtoVSucsV.cSB9IS5oDM()
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.BYuJEOF6yX1bIm30fBB(Object )
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve()
   at ESBasic.Helpers.EventHelper.SpringEventSafely(IAgileLogger agileLogger, String eventPath, Delegate theEvent) 。错误类型:System.Exception。位置：dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve() On handle event [ESFramework.Engine.Tcp.Passive.TcpEngine.ConnectionRebuildSucceed].


2019/5/13 15:34:28 : 普通 －－ Network connection is disconnected! [:]    at VY2WkBrATJKAS82x7vh.BPdVSJrxw6RMlYCfRpC.PickupResponse(Int32  , Int32  )
   at ksUUmTr8nYAtS5mI5Co.wyW5NXrMaaEwgBV24lX.iht9eSnX3R(aXwZLgSeWEc5DHdDVp8  , Nullable`1 resKey)
   at x8MZUsrTIhCCTcOQv02.agcZdrrgVBTtoVSucsV.cSB9IS5oDM()
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.BYuJEOF6yX1bIm30fBB(Object )
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve()
   at ESBasic.Helpers.EventHelper.SpringEventSafely(IAgileLogger agileLogger, String eventPath, Delegate theEvent) 。错误类型:System.Exception。位置：dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve() On handle event [ESFramework.Engine.Tcp.Passive.TcpEngine.ConnectionRebuildSucceed].


2019/5/14 9:16:26 : 普通 －－ Network connection is disconnected! [:]    at VY2WkBrATJKAS82x7vh.BPdVSJrxw6RMlYCfRpC.PickupResponse(Int32  , Int32  )
   at ksUUmTr8nYAtS5mI5Co.wyW5NXrMaaEwgBV24lX.iht9eSnX3R(aXwZLgSeWEc5DHdDVp8  , Nullable`1 resKey)
   at x8MZUsrTIhCCTcOQv02.agcZdrrgVBTtoVSucsV.cSB9IS5oDM()
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.BYuJEOF6yX1bIm30fBB(Object )
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve()
   at ESBasic.Helpers.EventHelper.SpringEventSafely(IAgileLogger agileLogger, String eventPath, Delegate theEvent) 。错误类型:System.Exception。位置：dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve() On handle event [ESFramework.Engine.Tcp.Passive.TcpEngine.ConnectionRebuildSucceed].


2019/5/14 9:35:58 : 普通 －－ Object reference not set to an instance of an object. [:]    at I7VeF2VvHTl7FAtaNtd.MHS4XkV6bjwMEHRPg2w.R1XP9LpC37p9n0dEwwe(Object )
   at I7VeF2VvHTl7FAtaNtd.MHS4XkV6bjwMEHRPg2w.seXOI19Se3()
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.Sw8ygYFl4tXLZ1SlJi8(Object )
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.Ye9DN4JDkO()
   at ESBasic.Helpers.EventHelper.SpringEventSafely(IAgileLogger agileLogger, String eventPath, Delegate theEvent) 。错误类型:System.NullReferenceException。位置：dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.Ye9DN4JDkO() On handle event [ESFramework.Engine.Tcp.Passive.TcpEngine.ConnectionInterrupted].


2019/5/14 9:43:45 : 普通 －－ Network connection is disconnected! [:]    at VY2WkBrATJKAS82x7vh.BPdVSJrxw6RMlYCfRpC.PickupResponse(Int32  , Int32  )
   at ksUUmTr8nYAtS5mI5Co.wyW5NXrMaaEwgBV24lX.iht9eSnX3R(aXwZLgSeWEc5DHdDVp8  , Nullable`1 resKey)
   at x8MZUsrTIhCCTcOQv02.agcZdrrgVBTtoVSucsV.cSB9IS5oDM()
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.BYuJEOF6yX1bIm30fBB(Object )
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve()
   at ESBasic.Helpers.EventHelper.SpringEventSafely(IAgileLogger agileLogger, String eventPath, Delegate theEvent) 。错误类型:System.Exception。位置：dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve() On handle event [ESFramework.Engine.Tcp.Passive.TcpEngine.ConnectionRebuildSucceed].


2019/5/14 9:45:26 : 普通 －－ Network connection is disconnected! [:]    at VY2WkBrATJKAS82x7vh.BPdVSJrxw6RMlYCfRpC.PickupResponse(Int32  , Int32  )
   at ksUUmTr8nYAtS5mI5Co.wyW5NXrMaaEwgBV24lX.iht9eSnX3R(aXwZLgSeWEc5DHdDVp8  , Nullable`1 resKey)
   at x8MZUsrTIhCCTcOQv02.agcZdrrgVBTtoVSucsV.cSB9IS5oDM()
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.BYuJEOF6yX1bIm30fBB(Object )
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve()
   at ESBasic.Helpers.EventHelper.SpringEventSafely(IAgileLogger agileLogger, String eventPath, Delegate theEvent) 。错误类型:System.Exception。位置：dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve() On handle event [ESFramework.Engine.Tcp.Passive.TcpEngine.ConnectionRebuildSucceed].


2019/5/14 9:49:57 : 普通 －－ Network connection is disconnected! [:]    at VY2WkBrATJKAS82x7vh.BPdVSJrxw6RMlYCfRpC.PickupResponse(Int32  , Int32  )
   at ksUUmTr8nYAtS5mI5Co.wyW5NXrMaaEwgBV24lX.iht9eSnX3R(aXwZLgSeWEc5DHdDVp8  , Nullable`1 resKey)
   at x8MZUsrTIhCCTcOQv02.agcZdrrgVBTtoVSucsV.cSB9IS5oDM()
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.BYuJEOF6yX1bIm30fBB(Object )
   at dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve()
   at ESBasic.Helpers.EventHelper.SpringEventSafely(IAgileLogger agileLogger, String eventPath, Delegate theEvent) 。错误类型:System.Exception。位置：dHTARxVc2MCGQxpD4uV.gCGjXVVJ2p4VYu2pSjs.fYyD78r4ve() On handle event [ESFramework.Engine.Tcp.Passive.TcpEngine.ConnectionRebuildSucceed].

